In [41]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/play-tennis/play_tennis.csv

In [42]:
import numpy as np 
import pandas as pd

In [43]:
df=pd.read_csv("/kaggle/input/play-tennis/play_tennis.csv")

In [44]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [45]:
df.drop(columns=["day"],inplace=True)

In [46]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [47]:
# Problem  Query
#outlook=Sunny,Temp=Hot,Humidity=High,Wind=Weak
# play=No or Yes

In [48]:
#Solution 
#P(Yes/Sunny,Hot,High,Weak)=P(Sunny/Yes)*P(Hot/Yes)*P(Humidity/Yes)*P(Wind/Yes)
#P(No/Sunny,Hot,High,Weak)=P(Sunny/No)*P(Hot/No)*P(Humidity/No)*P(Wind/No)

In [49]:
# Look up table will be created by naive bayes which will include p(everything)

In [50]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [51]:
Py=9/14
Pn=5/14

print(Py)
print(Pn)

0.6428571428571429
0.35714285714285715

In [52]:
# outlook 
pd.crosstab(df["outlook"],df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [53]:
Pon=0
Prn=2/5
Psn=3/5


Poy=4/9
Pry=3/9
Psy=2/9

In [54]:
pd.crosstab(df["temp"],df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [55]:
Pcn=1/5
Phn=2/5
Pmn=2/5

Pcy=3/9
Phy=2/9
Pmy=4/9

In [56]:
pd.crosstab(df["humidity"],df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [57]:
Phun=4/5
Pnon=1/5

Phuy=3/9
Pnuy=6/9

In [58]:
pd.crosstab(df["wind"],df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [59]:
Pstrn=3/5
Pwekn=2/5


Pstry=3/9
Pweky=6/9

In [60]:
# Query --> #outlook=Sunny,Temp=Hot,Humidity=High,Wind=Weak
#Solution 
#P(Yes/Sunny,Hot,High,Weak)=P(Sunny/Yes)*P(Hot/Yes)*P(Humidity/Yes)*P(Wind/Yes)
#P(No/Sunny,Hot,High,Weak)=P(Sunny/No)*P(Hot/No)*P(Humidity/No)*P(Wind/No)


prob_y=Psy*Phy*Phuy*Pweky

In [61]:
prob_y

0.010973936899862823

In [62]:
prob_n=Psn*Phn*Phun*Pwekn

In [63]:
prob_n

0.07680000000000001